

1.   Dos motos viajan a diferentes velocidades (**vel1** y **vel2**) y están distanciados por una distancia **dis**. La moto que se encuentra detrás lleva una velocidad mayor que la primera. Se pide realizar un script en python que solicite al usuario la distancia entre las motos en km y las velocidades de las mismas y con ello devolver en cuanto tiempo la moto 2 alcanzará a la moto 1.

In [ ]:
def tiempo_alcance(distancia, velocidad1, velocidad2):
    if velocidad2 <= velocidad1:
        return "La moto 2 nunca alcanzará a la moto 1, ya que no es más rápida."
    tiempo = distancia / (velocidad2 - velocidad1)
    return f"La moto 2 alcanzará a la moto 1 en {tiempo:.2f} horas."

# Solicitar datos al usuario
distancia = float(input("Ingrese la distancia entre las motos (km): "))
velocidad1 = float(input("Ingrese la velocidad de la moto 1 (km/h): "))
velocidad2 = float(input("Ingrese la velocidad de la moto 2 (km/h): "))

# Calcular y mostrar el resultado
resultado = tiempo_alcance(distancia, velocidad1, velocidad2)
print(resultado)

Ingrese la distancia entre las motos (km): 10
Ingrese la velocidad de la moto 1 (km/h): 10
Ingrese la velocidad de la moto 2 (km/h): 5
La moto 2 nunca alcanzará a la moto 1, ya que no es más rápida.


2. El tutor de 2º ASIR esta organizando un viaje a Granada, y requiere determinar cuánto debe cobrar a cada alumno y cuánto debe pagar a la agencia de viajes. La forma de cobrar es la siguiente: si son 100 alumnos o más, el costo por cada alumno es de 65 euros; de 50 a 99 alumnos, el costo es de 70 euros, de 30 a 49, de 95 euros, y si son menos de 30, el costo de la guagua es de 4000 euros, sin importar el número de alumnos. Realice un script que permita determinar el pago a la compañía de guaguas y lo que debe pagar cada alumno por el viaje.

In [ ]:
def calcular_costo_viaje(num_alum):
    if num_alum >= 100:
        costo_alum = 65
    elif num_alum >= 50:
        costo_alum = 70
    elif num_alum >= 30:
        costo_alum = 95
    else:
        if num_alum <= 0:
            return "No pueden venir menos de 1 alumno"
        costo_total = 4000
        costo_alum = costo_total / num_alum
        return costo_total, costo_alum

    costo_total = costo_alum * num_alum
    return costo_total, costo_alum

# Que ingrese por pantalla el parámetro
num_alum = int(input("Ingrese el número de alumnos que van a ir: "))

# Calcular y mostrar el resultado
resultado = calcular_costo_viaje(num_alum)
if isinstance(resultado, str):
    print(resultado)
else:
    costo_total, costo_alum = resultado
    print(f"El costo total ha sido de {costo_total} euros")
    print(f"Cada alumno debe poner {costo_alum} euros")


Ingrese el número de alumnos que van a ir: 33
El costo total ha sido de 3135 euros
Cada alumno debe poner 95 euros


3. Crea un script que permita adivinar un número. La aplicación genera un número aleatorio del 1 al 100. A continuación va pidiendo números y va respondiendo si el número a adivinar es mayor o menor que el introducido, además de los intentos que te quedan (tienes 10 intentos para acertarlo).  El programa termina cuando se acierta el número (además te dice en cuantos  intentos lo has acertado), si se llega al limite de intentos te muestra el  número que había generado.

In [ ]:
import random

intentosRealizados = 0

número = random.randint(1, 100)
print('Estoy pensando en un número entre 1 y 100.')

while intentosRealizados < 11:
    print('Intenta adivinar.')
    estimación = input()
    estimación = int(estimación)

    intentosRealizados = intentosRealizados + 1

    if estimación < número:
        print('Tu estimación es muy baja.')

    if estimación > número:
        print('Tu estimación es muy alta.')

    if estimación == número:
        break

if estimación == número:
    intentosRealizados = str(intentosRealizados)
    print('¡Buen trabajo! ¡Has adivinado mi número en ' + intentosRealizados + ' intentos!')

if estimación != número:
    número = str(número)
    print('Pues no. El número que estaba pensando era ' + número)


Estoy pensando en un número entre 1 y 20.
Intenta adivinar.
10
Tu estimación es muy baja.
Intenta adivinar.
15
Tu estimación es muy alta.
Intenta adivinar.
13
¡Buen trabajo! ¡Has adivinado mi número en 3 intentos!


In [ ]:
import random

def juego_adivinanza():
    numero_a_adivinar = random.randint(1, 100)
    intentos_maximos = 10
    intentos_realizados = 0

    print("\n¡Bienvenido al juego de adivinanza!")
    nombre = input("¿Cómo te llamas?: ")

    print(f"\nBueno, {nombre}, estoy pensando en un número entre 1 y 100.")
    print("Tienes 10 intentos para adivinarlo.")

    while intentos_realizados < intentos_maximos:
        print(f"\nIntento {intentos_realizados + 1} de {intentos_maximos}")

        try:
            estimacion = int(input("Introduce tu número: "))
        except ValueError:
            print("Entrada no válida. Ingresa un número entero.")
            continue

        if estimacion < 1 or estimacion > 100:
            print("Número fuera de rango (1-100). ¡Has perdido un intento!")
        else:
            intentos_realizados += 1

            if estimacion < numero_a_adivinar:
                print("Tu estimación es demasiado baja.")
            elif estimacion > numero_a_adivinar:
                print("Tu estimación es demasiado alta.")
            else:
                print(f"Felicidades, {nombre}! Adivinaste el número en {intentos_realizados} intentos.")
                if intentos_realizados <= 5:
                    print("¡Increíble! Lo lograste en muy pocos intentos.")
                return

        if intentos_realizados % 3 == 0 and intentos_realizados < intentos_maximos:
            pista = "par" if numero_a_adivinar % 2 == 0 else "impar"
            print(f"Pista: El número es {pista}.")

    print(f"Lo siento, {nombre}. Se te han acabado los intentos.")
    print(f"El número correcto era {numero_a_adivinar}.")

    jugar_de_nuevo = input("\n¿Quieres jugar otra vez? (s/n): ").lower()
    if jugar_de_nuevo == 's':
        juego_adivinanza()
    else:
        print("Gracias por jugar. Hasta la próxima.")

# Ejecutar el juego
juego_adivinanza()



¡Bienvenido al juego de adivinanza!
¿Cómo te llamas?: Alberto

Bueno, Alberto, estoy pensando en un número entre 1 y 100.
Tienes 10 intentos para adivinarlo.

Intento 1 de 10
Introduce tu número: 50
Tu estimación es demasiado alta.

Intento 2 de 10
Introduce tu número: 25
Tu estimación es demasiado baja.

Intento 3 de 10
Introduce tu número: 30
Tu estimación es demasiado alta.
Pista: El número es impar.

Intento 4 de 10
Introduce tu número: 20
Tu estimación es demasiado baja.

Intento 5 de 10
Introduce tu número: 36
Tu estimación es demasiado alta.

Intento 6 de 10
Introduce tu número: 9
Tu estimación es demasiado baja.
Pista: El número es impar.

Intento 7 de 10
Introduce tu número: 27
Tu estimación es demasiado baja.

Intento 8 de 10
Introduce tu número: 29
Felicidades, Alberto! Adivinaste el número en 8 intentos.


4. Realizar un script que pida una String por teclado que contenga espacios y devuelva el número de palabrás que contenga

In [ ]:
texto = input("Ponga la frase que quieras: ")

#Dividir la frase por palabras
palabras = texto.split()

#Contar las palabras
contar_palabras = len(palabras)

print(f"El número de palabras en el texto es de: {contar_palabras}")

Ponga la frase que quieras: hoy es un dia de mierda
El número de palabras en el texto es de: 6


5. Realiza un script que se le pasen 5 notas de un alumno por teclado (comprendidas entre 0 y 10). A continuación debe mostrar todas las notas, la nota media, la nota más alta que ha sacado y la menor.



In [ ]:
notas = []
for indice in range(1, 6):
    nota_valida = False
    while not nota_valida:
        nota = int(input("Introduce la nota %d: " % indice))
        if 0 <= nota <= 10:
            nota_valida = True
    notas.append(nota)

# Muestro resultados
print("Notas: ", end="")
for nota in notas:
    print(nota, " ", end="")
print()
print("Nota media: ", sum(notas) / len(notas))
print("Nota max: ", max(notas))
print("Nota min: ", min(notas))


Introduce la nota 1: 5
Introduce la nota 2: 6
Introduce la nota 3: 4
Introduce la nota 4: 1
Introduce la nota 5: 10
Notas: 5  6  4  1  10  
Nota media:  5.2
Nota max:  10
Nota min:  1


6. Realizar un script que cree una una tabla bidimensional de 5x5 y nombre 'diagonal'. La Componentes de la tabla en su diagonales deben de ser 1 y el resto 0. Se ha de mostrar el contenido de la tabla por pantalla.

In [ ]:
# Crear la matriz 5x5 con ceros
diagonal = [[0 for _ in range(5)] for _ in range(5)]

# Rellenar las diagonales con 1
for i in range(5):
    diagonal[i][i] = 1  # Diagonal principal
    diagonal[i][4 - i] = 1  # Diagonal secundaria

# Mostrar la matriz
print("Matriz 'diagonal':")
for fila in diagonal:
    print(" ".join(map(str, fila)))


Matriz 'diagonal':
1 0 0 0 1
0 1 0 1 0
0 0 1 0 0
0 1 0 1 0
1 0 0 0 1


7. Crea un script que pida un número y cree un diccionario cuyas claves sean desde el número 1 hasta el número indicado, y los valores sean los cuadrados de las claves.



In [ ]:
# Pedir un número al usuario
num = int(input("Ingrese un número: "))

# Crear el diccionario con claves y sus cuadrados como valores
diccionario = {i: i**2 for i in range(1, num + 1)}

# Mostrar el diccionario
print("Diccionario generado:")
print(diccionario)


Ingrese un número: 10
Diccionario generado:
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100}


8. Crea un script de una agenda en la que se guardan nombres y números de teléfono. En la agenda existirá un menú con las siguientes opciones:
 * **Añadir/modificar**: Nos pide un nombre. Si el nombre se encuentra en la agenda, debe mostrar el teléfono y, opcionalmente, permitir modificarlo si no es correcto. Si el nombre no se encuentra, debe permitir ingresar el teléfono correspondiente.
 * **Buscar**: Nos pide una cadena de caracteres, y nos muestras todos los contactos cuyos nombres comiencen por dicha cadena.
 * **Borrar**: Nos pide un nombre y si existe nos preguntará si queremos borrarlo de la agenda.
 * **Listar**: Nos muestra todos los contactos de la agenda.

  Implementar el script con un diccionario.

In [ ]:
def mostrar_menu():
    print("\nAGENDA TELEFÓNICA")
    print("1. Añadir/Modificar contacto")
    print("2. Buscar contacto")
    print("3. Borrar contacto")
    print("4. Listar contactos")
    print("5. Salir")

def agregar_modificar(agenda, nombre, telefono):
    agenda[nombre] = telefono

def buscar(agenda, cadena):
    return {nombre: telefono for nombre, telefono in agenda.items() if nombre.startswith(cadena)}

def borrar(agenda, nombre):
    if nombre in agenda:
        del agenda[nombre]
        return True
    return False

def listar(agenda):
    return agenda

def ejecutar_agenda():
    agenda = {}  # Diccionario para almacenar contactos
    opcion = None  # Inicializar la opción

    while opcion != "5":  # Se repite hasta que el usuario elija salir
        mostrar_menu()
        opcion = input("Seleccione una opción (1-5): ")

        if opcion == "1":  # Añadir/Modificar
            nombre = input("Ingrese el nombre: ").strip().capitalize()
            if nombre in agenda:
                print(f"El número actual de {nombre} es: {agenda[nombre]}")
                modificar = input("¿Desea modificarlo? (s/n): ").strip().lower()
                if modificar == "s":
                    telefono = input("Ingrese el nuevo número: ").strip()
                    agregar_modificar(agenda, nombre, telefono)
            else:
                telefono = input("Ingrese el número: ").strip()
                agregar_modificar(agenda, nombre, telefono)

        elif opcion == "2":  # Buscar
            cadena = input("Ingrese el inicio del nombre a buscar: ").strip().capitalize()
            resultados = buscar(agenda, cadena)
            if resultados:
                for nombre, telefono in resultados.items():
                    print(f"{nombre}: {telefono}")
            else:
                print("No se encontraron contactos.")

        elif opcion == "3":  # Borrar
            nombre = input("Ingrese el nombre a borrar: ").strip().capitalize()
            if borrar(agenda, nombre):
                print(f"{nombre} ha sido eliminado.")
            else:
                print("El contacto no existe.")

        elif opcion == "4":  # Listar
            contactos = listar(agenda)
            if contactos:
                for nombre, telefono in contactos.items():
                    print(f"{nombre}: {telefono}")
            else:
                print("La agenda está vacía.")

        elif opcion == "5":  # Salir
            print("Saliendo de la agenda.")

        else:
            print("Opción no válida.")

# Llamar a la función para ejecutar la agenda
ejecutar_agenda()



AGENDA TELEFÓNICA
1. Añadir/Modificar contacto
2. Buscar contacto
3. Borrar contacto
4. Listar contactos
5. Salir
Seleccione una opción (1-5): 1
Ingrese el nombre: alberto
Ingrese el número: 1234

AGENDA TELEFÓNICA
1. Añadir/Modificar contacto
2. Buscar contacto
3. Borrar contacto
4. Listar contactos
5. Salir
Seleccione una opción (1-5): 2
Ingrese el inicio del nombre a buscar: alberto
Alberto: 1234

AGENDA TELEFÓNICA
1. Añadir/Modificar contacto
2. Buscar contacto
3. Borrar contacto
4. Listar contactos
5. Salir
Seleccione una opción (1-5): 3
Ingrese el nombre a borrar: alberto
Alberto ha sido eliminado.

AGENDA TELEFÓNICA
1. Añadir/Modificar contacto
2. Buscar contacto
3. Borrar contacto
4. Listar contactos
5. Salir
Seleccione una opción (1-5): 4
La agenda está vacía.

AGENDA TELEFÓNICA
1. Añadir/Modificar contacto
2. Buscar contacto
3. Borrar contacto
4. Listar contactos
5. Salir
Seleccione una opción (1-5): 1
Ingrese el nombre: alberto
Ingrese el número: 4

AGENDA TELEFÓNICA
1. Aña

9. Crear un script que al introducir una fecha nos diga a que día juliano corresponde. El día juliano correspondiente a una fecha es un número entero que indica los días que han transcurrido desde el 1 de enero.Para ello debes de hacer las siguientes funciones:
 * **LeerFecha**: Lee por teclado el día, mes y el año.
 * **DiasDelMes**: Recibe un mes y un año y devuelve el número de días
 * **EsBisiesto**: Recibido un año nos dice si es bisiesto o no.
 * **Calcular_Dia_Juliano**: Recibe una fecha y nos devuelve el día juliano.

In [ ]:
def LeerFecha():
    dia = int(input("Introduce el día: "))
    mes = int(input("Introduce el mes: "))
    año = int(input("Introduce el año: "))
    return dia, mes, año

def EsBisiesto(año):
    """Determina si un año es bisiesto"""
    return (año % 4 == 0 and año % 100 != 0) or (año % 400 == 0)

def DiasDelMes(mes, año):
    """Devuelve la cantidad de días de un mes dado en un año específico"""
    if mes in [1, 3, 5, 7, 8, 10, 12]:
        return 31
    elif mes in [4, 6, 9, 11]:
        return 30
    elif mes == 2:
        return 29 if EsBisiesto(año) else 28
    else:
        return -1  # Valor inválido

def Calcular_Dia_Juliano(dia, mes, año):
    """Calcula el día juliano en base a una fecha dada"""
    total_dias = dia
    for m in range(1, mes):
        total_dias += DiasDelMes(m, año)
    return total_dias

# Programa principal
fecha = LeerFecha()
dia_juliano = Calcular_Dia_Juliano(fecha[0], fecha[1], fecha[2])
print("El día juliano correspondiente a la fecha es:", dia_juliano)


Introduce el día: 20
Introduce el mes: 10
Introduce el año: 2025
El día juliano correspondiente a la fecha es: 293



10. Función CalcularMCD: Recibe dos números y devuelve el MCD utilizando el método de Euclides.
El método de Euclides es el siguiente:
 * Se divide el número mayor entre el menor.
 * Si la división es exacta, el divisor es el MCD.
 * Si la división no es exacta, dividimos el divisor entre el resto obtenido y se continúa de esta forma hasta obtener una división exacta, siendo el último divisor el MCD.


In [ ]:
import numpy as np

# Crear una matriz 5x5 con valores progresivos
def generar_matriz_5x5():
    valor = 1  # Comienza en 1
    matriz = np.zeros((5, 5))  # Matriz vacía de 5x5

    for i in range(5):
        for j in range(5):
            matriz[i, j] = valor
            valor += 1  # Incremento progresivo

    return matriz

# Obtener la matriz
matriz = generar_matriz_5x5()

# Calcular el determinante
determinante = np.linalg.det(matriz)

# Imprimir matriz y determinante
print("Matriz generada:")
print(matriz)
print(f"\nDeterminante de la matriz: {determinante:.2f}")


Matriz generada:
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25.]]

Determinante de la matriz: 0.00


https://plataforma.josedomingo.org/pledin/cursos/programacion_python3/curso/u29/